# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/krunner': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/kontactinterface' : '@same'

Options:
  ctest-arguments: '--repeat until-pass:3'
  use-ccache: True
  require-passing-tests-on: [Linux']
  gcovr-arguments: '--filter src/'

