version = 1
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
SPDX-PackageName = "zanshin"
SPDX-PackageSupplier = "Kevin Ottens <ervin@kde.org>"
SPDX-PackageDownloadLocation = "https://zanshin.kde.org/"
annotations = ["REUSE.toml"]
